career_mysql:
    image: mysql:8.0
    restart: always
    command: --default-authentication-plugin=mysql_native_password --mysqlx=0
    environment:
      - MYSQL_PORT=5306  # cannot change this port to other number
      - MYSQL_DATABASE=career_wky # name you want for the database
      - MYSQL_USER=root # change to whatever username you wantr
      - MYSQL_ROOT_PASSWORD=Alex12345 #change to good root password
    volumes:
      - "./db:/var/lib/mysql"
      - "./sql:/sql"


career_nginx:
  restart: always
  image: nginx
  ports:
    - "8002:80"
  volumes:
    - ./conf/nginx.conf:/etc/nginx/conf.d/nginx.conf
  volumes_from:
    - career_wky
  links:
    - career_wky:web

career_wky:
  restart: always
  build: .
  environment:
    - use_docker=1
  volumes:
    - .:/ProjectPath
    - ./conf/uwsgi.ini:/etc/uwsgi.ini
  links:
    - career_mysql:mysql
  command: uwsgi -i /etc/uwsgi.ini